ControleAtividades/Controllers/PublicacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Repository.Controllers;
using Repository.Logic;
using Domain.Model;
using System.Linq.Expressions;
using Domain.Model.ViewModel;
using Util;
using System.Net;
using System.IO;

namespace Controleca_atividades.Controllers
{
    public class PublicacaoController : BaseController<ca_publicacao>
    {
        GenericRepository<ca_atividadesPublicadas> repositorioAP = new GenericRepository<ca_atividadesPublicadas>();
        GenericRepository<ca_atividade> repositorioA = new GenericRepository<ca_atividade>();

        Expression<Func<ca_atividade, bool>> whereA;
        Expression<Func<ca_usuario, bool>> whereCAU;
        Expression<Func<ca_atividade, bool>> atividadesFinalizadas_e_NaoPublicadas = a => a.dt_inicio.HasValue && a.dt_fim.HasValue && !a.ca_atividadesPublicadas.Any();
        Expression<Func<ca_atividadesPublicadas, bool>> whereAP;

        [HttpGet]
        [OutputCache(NoStore = true, Duration = 0)]
        public ActionResult Index(string page, string sort, string sortdir)
        {
            ViewBag.Incluir = "Novo";

            return View(Consultar(page, sort, sortdir));
        }

        [HttpPost]
        [OutputCache(NoStore = true, Duration = 0)]
        public ActionResult Index(string page, string sort, string sortdir, string filtro)
        {
            ViewBag.Incluir = "Novo";

            return View(Consultar(page, sort, sortdir, filtro));
        }

        private GridVM Consultar(string page, string sort, string sortdir, string filtro = null)
        {
            if (string.IsNullOrWhiteSpace(filtro))
                where = p => true;
            else
                where = p => p.sistema.Contains(filtro) || p.ca_atividadesPublicadas.Count(ap => ap.ca_atividade.descricao.Contains(filtro)) > 0;

            GridVM grid = new GridVM();
            List<ca_publicacaoVM> publicacoes = new List<ca_publicacaoVM>();
            IQueryable<ca_publicacao> aux;
            aux = repositorio.Listar(where).OrderBy(u => u.dt_publicacao);

            int pagina = 0;
            int totalRegistros = repositorio.Listar(where).Count();

            grid.PageLimit = base.pageLimit;
            grid.PageSize = base.pageSize;

            if (totalRegistros > base.pageSize)
                grid.TotalPages = int.Parse((totalRegistros / base.pageSize).ToString()) + 1;
            else
            {
                page = "1";
                grid.TotalPages = 1;
            }

            if (Int32.TryParse(page, out pagina))
                aux = aux.Skip((pagina - 1) * base.pageSize).Take(base.pageSize);
            else
                aux = aux.Take(base.pageSize);

            grid.PageIndex = pagina;

            foreach (var item in aux)
            {
                var publicacao = new ca_publicacaoVM();

                publicacao.usuario = item.ca_usuario.nome;
                publicacao.dt_publicacao = item.dt_publicacao.HasValue ? item.dt_publicacao.Value.ToShortDateString() : "Não publicado";
                publicacao.sistema = item.sistema;

                var atividades = item.ca_atividadesPublicadas.Select(ap => ap.ca_atividade);

                foreach (var atividade in atividades)
                {
                    string texto = "<strong>Prioridade:</strong> " + atividade.prioridade
                        + "<br /><strong>Período: </strong> " + (atividade.dt_inicio.HasValue ? atividade.dt_inicio.Value.ToShortDateString() : "--/--/----")
                        + " <strong>até</strong> " + (atividade.dt_fim.HasValue ? atividade.dt_fim.Value.ToShortDateString() : "--/--/----")
                        + "<br /><strong>Descrição:</strong> " + atividade.descricao;

                    if (string.IsNullOrWhiteSpace(publicacao.atividades))
                        publicacao.atividades += texto;
                    else
                        publicacao.atividades += "<br /><br />" + texto;
                }

                publicacao.operacoes =
                    "<span style='padding-right: 3px;'><a href='#' class='btn btn-info' href='#' onclick='alterar(" + item.id
                    + ");'><i class='icon-white icon-edit'></i></a></span>"
                    + "<br /><br />"
                    + "<span style='padding-right: 3px;'><a href='#' class='btn btn-danger' onclick='excluir(" + item.id
                    + ");'><i class='icon-white icon-trash'></i></a></span>";

                publicacoes.Add(publicacao);
            }


            grid.Lista = publicacoes;
            grid.Tipo = typeof(ca_publicacaoVM);

            return grid;
        }

        [HttpGet]
        public ActionResult Incluir()
        {
            PreencherVBInclusao();

            ViewBag.Submit = "Incluir";
            ViewBag.BotaoSubmit = "primary";
            ViewBag.Voltar = "Voltar";

            return View(new ca_publicacao());
        }

        [HttpPost]
        public ActionResult Incluir(FormCollection form)
        {
            try
            {
                ViewBag.Submit = "Incluir";
                ViewBag.BotaoSubmit = "primary";
                ViewBag.Voltar = "Voltar";

                ca_publicacao publicacao = new ca_publicacao();
                TryUpdateModel(publicacao, form);

                if (ViewData.ModelState.IsValid)
                {
                    ca_atividadesPublicadas atividadePublicada;

                    foreach (var item in form.AllKeys.Where(f => f.Contains("Atividade_")))
                    {
                        if (form[item].Contains("true"))
                        {
                            atividadePublicada = new ca_atividadesPublicadas();
                            atividadePublicada.id_publicacao = publicacao.id;
                            atividadePublicada.id_atividade = int.Parse(item.Replace("Atividade_", ""));

                            publicacao.ca_atividadesPublicadas.Add(atividadePublicada);
                        }
                    }

                    repositorio.Incluir(publicacao);
                    repositorio.Salvar();

                    EmailPublicacao(publicacao);

                    Mensagem(TipoMensagem.Sucesso, "Publicação realizada com sucesso!");

                    return RedirectToAction("Index");
                }
                else
                {
                    PreencherVBInclusao();

                    Mensagem(TipoMensagem.Aviso, "Preencha os campos corretamente");

                    return View(publicacao);
                }
            }
            catch (Exception ex)
            {
                Mensagem(TipoMensagem.Erro, "ERRO: " + ex.Message);

                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public ActionResult Alterar(int id)
        {
            try
            {
                where = i => i.id == id;

                ca_publicacao publicacao = repositorio.Obter(where);

                ViewBag.Submit = "Alterar";
                ViewBag.BotaoSubmit = "warning";
                ViewBag.Voltar = "Voltar";

                if (publicacao != null)
                {
                    PreencherVBAlteracao(publicacao);

                    return View(publicacao);
                }
                else
                {
                    Mensagem(TipoMensagem.Erro, "ERRO: Não foi possível encontrar a Publicação(id = " + id + ").");

                    return View("Index");
                }
            }
            catch (Exception ex)
            {
                Mensagem(TipoMensagem.Erro, "ERRO: " + ex.Message);

                return View("Index");
            }
        }

        [HttpPost]
        public ActionResult Alterar(FormCollection form)
        {
            try
            {
                ViewBag.Submit = "Alterar";
                ViewBag.BotaoSubmit = "warning";
                ViewBag.Voltar = "Voltar";

                ca_publicacao publicacao = new ca_publicacao();
                TryUpdateModel(publicacao, form);

                if (ViewData.ModelState.IsValid)
                {
                    #region Adicionando e Removendo AtividesPublicadas

                    whereAP = ap => ap.id_publicacao == publicacao.id;
                    List<ca_atividadesPublicadas> apAntigas = repositorioAP.Listar(whereAP).ToList();
                    List<int> naoAdicionar = new List<int>();
                    ca_atividadesPublicadas atividadePublicada;

                    foreach (var antigas in apAntigas)
                    {
                        bool achou = false;

                        foreach (var item in form.AllKeys.Where(f => f.Contains("Atividade_")))
                        {
                            atividadePublicada = new ca_atividadesPublicadas();

                            if (form[item].Contains("true"))
                            {
                                if (antigas.id_atividade == int.Parse(item.Replace("Atividade_", "")))
                                    achou = true;
                            }
                        }

                        if (achou)
                            naoAdicionar.Add(antigas.id_atividade);
                        else
                            repositorioAP.Deletar(antigas);
                    }

                    repositorioAP.Salvar();

                    foreach (var item in form.AllKeys.Where(f => f.Contains("Atividade_")))
                    {
                        atividadePublicada = new ca_atividadesPublicadas();

                        if (form[item].Contains("true"))
                        {
                            if (!naoAdicionar.Any(n => n == int.Parse(item.Replace("Atividade_", ""))))
                            {
                                atividadePublicada.id_publicacao = publicacao.id;

ControleAtividades/Views/Shared/Botoes.cshtml
<div id="botoes" style="margin-top: 150px;">
    @{
        if (!string.IsNullOrEmpty(ViewBag.Submit) && !string.IsNullOrEmpty(ViewBag.BotaoSubmit))
        {
        <input type="submit" value="@ViewBag.Submit" class="btn btn-@ViewBag.BotaoSubmit btn-large" />
        <br />
        <br />
        }
        if (!string.IsNullOrEmpty(ViewBag.Incluir))
        {
        @Html.ActionLink(ViewBag.Incluir as string, "Incluir", null, new { @class = "btn btn-primary btn-large" })
        <br />
        <br />
        }
        if (!string.IsNullOrEmpty(ViewBag.Alterar))
        {
        @Html.ActionLink(ViewBag.Alterar as string, "Alterar", null, new { @class = "btn btn-info btn-large" })
        <br />
        <br />
        }
        if (!string.IsNullOrEmpty(ViewBag.Excluir))
        {
        @Html.ActionLink(ViewBag.Excluir as string, "Excluir", null, new { @class = "btn btn-danger btn-large" })
        <br />
        <br />
        }
        if (!string.IsNullOrEmpty(ViewBag.Voltar))
        {
        @Html.ActionLink(ViewBag.Voltar as string, "Index", null, new { @class = "btn btn-inverse btn-large" })
        }
    }
</div>

ControleAtividades/Views/Shared/Grid.cshtml
@model Domain.Model.ViewModel.GridVM
@using System.ComponentModel
@using Domain.Model.ViewModel
@{
    WebGrid grid = new WebGrid(Model.Lista, ajaxUpdateContainerId: "grid", rowsPerPage: Model.PageSize);
    List<WebGridColumn> cols = new List<WebGridColumn>();

    var props = Model.Tipo.GetProperties().Where(p => !p.PropertyType.FullName.Contains("EntityReference")
        && !p.PropertyType.FullName.Contains("EntityCollection")
        && !p.PropertyType.FullName.Contains("EntityState")
        && !p.PropertyType.FullName.Contains("EntityKey"));

    foreach (var prop in props)
    {
        var nomeExibir = "";
        var name = prop.Name;

        if (prop.GetCustomAttributes(true).Count() > 0 && prop.GetCustomAttributes(true).ElementAt(0) is DisplayNameAttribute)
        {
            nomeExibir = ((DisplayNameAttribute)(prop.GetCustomAttributes(true).ElementAt(0))).DisplayName;
        }
        else
        {
            nomeExibir = prop.Name;
        }

        cols.Add(grid.Column(
            name,
            nomeExibir,
            format: i => Html.Raw(i[name])
            ));
    }

    PaginacaoVM paginacao = new PaginacaoVM();

    paginacao.PageIndex = Model.PageIndex;
    paginacao.TotalPages = Model.TotalPages;
    paginacao.PageLimit = Model.PageLimit;

    Tuple<WebGrid, PaginacaoVM> parametro = new Tuple<WebGrid, PaginacaoVM>(grid, paginacao);
    
@*@Html.Partial("Paginacao", parametro);*@
                                    
    <div id="grid">@grid.GetHtml(
              tableStyle: "table", // table-condensed
                    footerStyle: "paginacao_hide",
                    columns: cols,
                    mode: WebGridPagerModes.All,
                    numericLinksCount: 5
                    )
    </div>
    
    
    @Html.Partial("Paginacao", parametro);
}

ControleAtividades/Views/Shared/Layout_MenuLateral.cshtml
@{
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}
@Styles.Render("~/Content/Views/Shared/Layout_MenuLateral.css")
<div class="container-fluid">
    <div class="row-fluid">
        @using (Html.BeginForm())
        {
            <div id="menuLateral" class="span3" style="float: left; position: fixed;">
                @Html.Partial("MenuLateral")
            </div>
            <div id="conteudoPagina" class="span8 offset3">
                @RenderBody()
            </div>
        }
    </div>
</div>
<div id="footer">
    <li>
        <ul>
            <h5>
                Controle de Atividades - Versão 2.0</h5>
        </ul>
        <ul>
            Desenvolvido por: caioff e filipebsouza
        </ul>
        <ul>
            2013 - 2014
        </ul>
    </li>
</div>

ControleAtividades/Views/Shared/Layout_Seguranca.cshtml
<style type="text/css">
    body
    {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #eee;
    }
    
    .form-signin
    {
        max-width: 40%;
        padding: 15px;
        margin: 0 auto;
    }
    .form-signin .form-signin-heading, .form-signin .checkbox
    {
        margin-bottom: 10px;
    }
    .form-signin .checkbox
    {
        font-weight: normal;
    }
    .form-signin .form-control
    {
        position: relative;
        font-size: 16px;
        height: auto;
        padding: 10px;
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
    }
    .form-signin .form-control:focus
    {
        z-index: 2;
    }
    .form-signin input[type="text"]
    {
        margin-bottom: -1px;
        border-bottom-left-radius: 0;
        border-bottom-right-radius: 0;
    }
    .form-signin input[type="password"]
    {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
    }
</style>
@{
    Layout = "~/Views/Shared/MasterLayout.cshtml";
}
<div class="container">
    @RenderBody()
</div>

ControleAtividades/Views/Shared/MasterLayout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    @Styles.Render("~/Content/bootstrap/css/bootstrap.min.css")
    @Styles.Render("~/Content/bootstrap/css/bootstrap-responsive.min.css")
    @Scripts.Render("~/Scripts/jQuery/jquery-1.8.2.min.js")
    @Scripts.Render("~/Scripts/bootstrap/bootstrap.min.js")
    @Scripts.Render("~/Scripts/Views/Shared/FuncoesLayout.js")
    @Scripts.Render("~/Scripts/util/Funcoes.js")
    <script type="text/javascript">
        var content = '@Url.Content("~/")';
        var controller = '@ViewBag.Controller' + '/';
    </script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div id="result">
        @{
            if (TempData["Sucesso"] != null)
            {
            <div class='alert alert-success'>
                @Html.Raw(TempData["Sucesso"])
            </div>
            }
            else if (TempData["Aviso"] != null)
            {
            <div class='alert'>
                @Html.Raw(TempData["Aviso"])
            </div>
            }
            else if (TempData["Erro"] != null)
            {
            <div class='alert alert-error'>
                @Html.Raw(TempData["Erro"])
            </div>
            }
        }
    </div>
    @RenderBody()
</body>
</html>

ControleAtividades/Views/Shared/MenuLateral.cshtml
<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel" style="display: block;
    position: static; width: 250px; margin-top: 5%;">
    <li class="dropdown-submenu">
        @Html.ActionLink("Atividade", "Index", "Atividade")
        <ul class="dropdown-menu">
            <li>
                @Html.ActionLink("Incluir", "Incluir", "Atividade")
            </li>
        </ul>
    </li>
    <li class="dropdown-submenu">
        @Html.ActionLink("Usuario", "Index", "Usuario")
        <ul class="dropdown-menu">
            <li>
                @Html.ActionLink("Incluir", "Incluir", "Usuario")
            </li>
        </ul>
    </li>
    <li class="dropdown-submenu">
        @Html.ActionLink("Publicação", "Index", "Publicacao")
        <ul class="dropdown-menu">
            <li>
                @Html.ActionLink("Incluir", "Incluir", "Publicacao")
            </li>
        </ul>
    </li>
    <li class="divider"></li>
    <li class="dropdown-submenu">
        @Html.ActionLink("Sair", null)
        <ul class="dropdown-menu">
            <li>
                @Html.ActionLink("SIM!", "Sair", "Seguranca")
            </li>
        </ul>
    </li>
</ul>
<br />
@Html.Partial("Botoes")

ControleAtividades/Views/Shared/ModalExclusao.cshtml
<div id="ModalExclusao" class="modal hide fade">
    @Html.Hidden("id")
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
            &times;</button>
        <h3>
            Excluir</h3>
    </div>
    <div class="modal-body">
        <p>
            Tem certeza que deseja excluir esse registro?</p>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn btn-danger" onclick="confirmarExclusao();">Confirmar exclusão</a>
        <a href="#" class="btn btn-inverse" data-dismiss="modal">Cancelar</a>
    </div>
</div>
@Scripts.Render("~/Scripts/Views/Shared/ModalExclusao.js")

ControleAtividades/Views/Shared/ModalMensagem.cshtml
<div id="ModalMensagem" class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
            &times;</button>
        <h3 id="txtTitleModalMensagem"></h3>
    </div>
    <div class="modal-body">
        <p id="txtModalMensagem"></p>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn btn-info" data-dismiss="modal">Ok</a>
    </div>
</div>

ControleAtividades/Views/Shared/Paginacao.cshtml
@model Tuple<WebGrid, Domain.Model.ViewModel.PaginacaoVM>
@{
    var numeroDePaginasPorView = Model.Item2.PageLimit;
    var iniciaEm = 1;
    var terminaEm = numeroDePaginasPorView;
    var totalDePaginas = Model.Item2.TotalPages;
    var paginaAtual = Model.Item2.PageIndex == 0 ? 1 : Model.Item2.PageIndex;
    var html = "";

    if (totalDePaginas > numeroDePaginasPorView)
    {
        if (paginaAtual + numeroDePaginasPorView - 1 > totalDePaginas)
        {
            iniciaEm = totalDePaginas - numeroDePaginasPorView;
            terminaEm = totalDePaginas;
        }
        else
        {
            iniciaEm = paginaAtual;
            terminaEm = paginaAtual + numeroDePaginasPorView - 1;
        }
    }
    else
    {
        terminaEm = totalDePaginas;
    }

    if (paginaAtual > 1)
    {
        html += "<li><a href='" + Url.Content("~/") + ViewBag.Controller + "?page=1'>Primeiro</a></li>";
        html += "<li><a href='" + Url.Content("~/") + ViewBag.Controller + "?page=" + (paginaAtual - 1) + "'>Anterior</a></li>";
    }

    for (int i = iniciaEm; i <= terminaEm; i++)
    {
        if (i != paginaAtual)
        {
            html += "<li><a href='" + Url.Content("~/") + ViewBag.Controller + "?page=" + (i) + "'>" + i + "</a></li>";
        }
        else
        {
            html += "<li class='disabled'><span>" + i + "</span></li>";
        }
    }

    if (paginaAtual < totalDePaginas)
    {
        html += "<li><a href='" + Url.Content("~/") + ViewBag.Controller + "?page=" + (paginaAtual + 1) + "'>Próximo</a></li>";
        html += "<li><a href='" + Url.Content("~/") + ViewBag.Controller + "?page=" + totalDePaginas + "'>Último</a></li>";
    }

}
<div class="span8 pagination pagination-large">
    <ul>@Html.Raw(html)</ul>
</div>
@Scripts.Render("~/Scripts/Views/Shared/Paginacao.js")

ControleAtividades/Views/Shared/PickDate.cshtml
@Styles.Render("~/Content/pickdate/default.css")
@Styles.Render("~/Content/pickdate/default.date.css")
@Styles.Render("~/Content/pickdate/rtl.css")
@Scripts.Render("~/Scripts/pickdate/picker.js")
@Scripts.Render("~/Scripts/pickdate/picker.date.js")
@Scripts.Render("~/Scripts/pickdate/legacy.js")
@Scripts.Render("~/Scripts/pickdate/pt_BR.js")